# Generated by Django 6.0.1 on 2026-01-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refillrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
