# Generated by Django 6.0.1 on 2026-01-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('PROVIDER', 'Provider'), ('STAFF', 'Staff')], max_length=20),
        ),
    ]
