# Generated by Django 6.0.1 on 2026-02-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('PROVIDER', 'Provider'), ('STAFF', 'Staff')], default='PATIENT', max_length=20),
        ),
    ]
